services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-sentence-splitter
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./upload_data:/app/upload_data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_WORKERS=1  # 可根據需求調整
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 如果需要 Redis 來支援 WebSocket 或進度管理
  redis:
    image: redis:alpine
    container_name: pdf-splitter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 